development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:ef6b98fcddfc5aed5713b70ab5af166c@tetra.redistogo.com:9681/
  #channel_prefix: message_me_production
